# Generated by Django 6.0.4 on 2026-05-10 11:12

import apps.trading.managers
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('tier', models.CharField(default='Professional', max_length=32)),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('10000.00000000'), max_digits=20)),
                ('total_pnl', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['email'],
            },
            managers=[
                ('objects', apps.trading.managers.DashboardUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=24, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('quote_currency', models.CharField(default='USD', max_length=8)),
                ('min_lot', models.DecimalField(decimal_places=4, max_digits=12)),
                ('lot_step', models.DecimalField(decimal_places=4, max_digits=12)),
                ('price_precision', models.PositiveSmallIntegerField(default=2)),
                ('quantity_precision', models.PositiveSmallIntegerField(default=2)),
                ('current_bid', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('current_ask', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('current_last', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('last_tick_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'instruments',
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['symbol'], name='instrument_symbol_idx'), models.Index(fields=['is_active'], name='instrument_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.JSONField()),
                ('session_stats', models.JSONField()),
                ('quotes', models.JSONField()),
                ('captured_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_snapshots',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['user', 'captured_at'], name='dash_snapshot_user_idx')],
            },
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timeframe', models.CharField(default='1m', max_length=12)),
                ('bucket_start', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='trading.instrument')),
            ],
            options={
                'db_table': 'candles',
                'ordering': ['bucket_start'],
                'indexes': [models.Index(fields=['instrument', 'timeframe', 'bucket_start'], name='candles_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('instrument', 'timeframe', 'bucket_start'), name='candles_instr_tf_bucket_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ActiveTrade',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('lot_size', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0100'))])),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('current_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('stop_loss', models.DecimalField(decimal_places=8, max_digits=20)),
                ('take_profit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('opened_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_trades', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_trades', to='trading.instrument')),
            ],
            options={
                'db_table': 'active_trades',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['user', 'opened_at'], name='active_trade_user_idx'), models.Index(fields=['instrument', 'opened_at'], name='active_trade_instr_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceTick',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('source_timestamp', models.DateTimeField()),
                ('bid', models.DecimalField(decimal_places=8, max_digits=20)),
                ('ask', models.DecimalField(decimal_places=8, max_digits=20)),
                ('last', models.DecimalField(decimal_places=8, max_digits=20)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_ticks', to='trading.instrument')),
            ],
            options={
                'db_table': 'price_ticks',
                'ordering': ['instrument__symbol', 'sequence'],
                'indexes': [models.Index(fields=['instrument', 'sequence'], name='tick_instr_seq_idx'), models.Index(fields=['source_timestamp'], name='tick_timestamp_idx')],
                'constraints': [models.UniqueConstraint(fields=('instrument', 'sequence'), name='tick_instr_sequence_uniq')],
            },
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('lot_size', models.DecimalField(decimal_places=4, max_digits=12)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('exit_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('stop_loss', models.DecimalField(decimal_places=8, max_digits=20)),
                ('take_profit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField()),
                ('pnl', models.DecimalField(decimal_places=8, max_digits=20)),
                ('pnl_percent', models.DecimalField(decimal_places=4, max_digits=12)),
                ('result', models.CharField(choices=[('WIN', 'Win'), ('LOSS', 'Loss')], max_length=8)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_history', to='trading.instrument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trade_history',
                'ordering': ['-closed_at'],
                'indexes': [models.Index(fields=['user', 'closed_at'], name='trade_hist_user_idx'), models.Index(fields=['instrument', 'closed_at'], name='trade_hist_instr_idx')],
            },
        ),
        migrations.CreateModel(
            name='TradingSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=16)),
                ('starting_balance', models.DecimalField(decimal_places=8, max_digits=20)),
                ('current_equity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='session_user_status_idx'), models.Index(fields=['started_at'], name='session_started_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebsocketConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=255, unique=True)),
                ('subscribed_channels', models.JSONField(default=list)),
                ('subscribed_symbols', models.JSONField(default=list)),
                ('connected_at', models.DateTimeField()),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected')], default='CONNECTED', max_length=16)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='websocket_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'websocket_connections',
                'ordering': ['-connected_at'],
                'indexes': [models.Index(fields=['status', 'connected_at'], name='ws_status_connected_idx')],
            },
        ),
    ]
